name: Harjoitus 3.2.2
on: push
permissions:
  contents: write
env:
  MY_KEYWORD: AuthorStamp
jobs:
  repo-test:
    runs-on: ubuntu-latest
    steps:
      # Haetaan repon koodit
      - uses: actions/checkout@v7
      - name: Check file
      # Jos ei tiedostoa vielä ole, kirjoitetaan sinne aluksi 0
      # Tämä on bonus. Tiedoston voi myös käsin luoda repoon aluksi arvolla 0.
      ## If-lauseke on bash-sriptauksessa käytettävä ehto.
        run: |  
          if [ ! -f counter.txt ]; then 
            echo "0" > counter.txt
          fi
      # Päivitetään counter ja viedään muutos repoon
      - name: Update counter
        run: |
          COUNT=$(cat counter.txt)
          COUNT=$((COUNT+1))
          echo "$COUNT" > counter.txt
          git config --global user.name 'repenaattori'
          git config --global user.email 'reimarii@oamk.fi'
          git add counter.txt
          git commit -m 'Push counter update'
          git push

          
          
