name: Harjoitus 3.3
on: 
  issues:
    types: opened
permissions:
  contents: write
jobs:
  repo-test:
    runs-on: ubuntu-latest
    steps:
      # Haetaan repon koodit
      - uses: actions/checkout@v7
      - name: Write issue
      # Lisätään issuen title ja asssignee README-tiedostoon.
        run: |  
          TITLE="${{github.event.issue.title}}"
          ASSIGNEE="${{github.event.issue.assignee.login}}"
          echo "Title: $TITLE  Assignee: $ASSIGNEE"
          echo "<br>$TITLE : $ASSIGNEE" >> README.md
      - name: Push into the repo
        run: |
          git config --global user.name 'repenaattori'
          git config --global user.email 'reimarii@oamk.fi'
          git add README.md
          git commit -m 'Issue information into the README'
          git push
        
          
          